### ISSUE TITLE
Non compatible change support

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifxml#37]
@ttl269 @throttlekitty @jonwd7 @GhostWalker71 @deedes @skyfox69 
Just getting the ball rolling.

As per the discussion in #24 EE2 AoS breaks general nif format by not incrementing the user version, such that the version differences can't be detected through normal condition checking.

I mod EE2 models ok, but i cant do with the expansion (Art of Supremacy) models, when i open AoS models appears this error: ""array Properties much too large. 16777216 bytes requested"" 
"failed to load block number 0 (NiNode) previous block was NiHeader" 
""infinite recursive link construct detected 0 -> 0"" 
"failed to load nif from 'C:/Documents and Settings/GONGALO/Configuración local/Temp/Rar$DI97.584/civ10_cuirassier_French.nifcache'"

**Comment by jonwd7** [comment]
I came back around to this issue while increasing the versions my 010 templates support and found the real issue.  Simply put, the 10.2.0.0 NIFs in ee2x are actually 10.1.0.0 in practice.

NiObject is actually like so (in 010 template format):
```c
typedef struct {
    if ( version >= V10_0_0_0 && version < V10_1_0_114 )
        uint groupID;
} NiObject;
```
So any NIF that is 10.0 or 10.1 will get the Group ID at the front of every single block, since every single block inherits NiObject.   However, the ee2x 10.2 NIFs will only load if you treat them as if they are 10.1.  As established there is no way to compensate for this in nif.xml since there is no differentiating factor. 

Given this, I believe this should just be closed.   Issue 2 in the above comment is another issue entirely, and the only way to resolve this issue is external to nif.xml.   Some kind of **compatibility mode in the parsers** for 10.2 NIFs where it attempts to also load them as 10.1 if 10.2 fails.
